name: MyWorkFlow

on:
  push:
    branches:
      - main  # or whichever branch you want to trigger on
jobs:
  example:
    runs-on: ubuntu-latest
   
    steps:
      - name: print welcome to the screen
        run: echo "Welcome to our first Github action"

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: List Repo Files
        run: ls -la
         
